import turtle
laki=turtle.Turtle()
laki.shape('turtle')
laki.color('pink')
laki.width(3)
laki.penup()
laki.goto(-100,-100)
laki.pendown()
laki.forward(200)
laki.left(90)
laki.forward(200)
laki.left (90)
laki.forward(200)
laki.left(90)
laki.forward(200)